#!/bin/bash

set -eu

if [ $# -lt 2 ]; then
  echo "USAGE: $0 <user>@<host> <local script> [argument ...]"
  exit 2
fi

remote="$1"
script="$2"

shift 2

temp="$(ssh -C "${remote}" 'temp="$(mktemp)"; chmod +x "${temp}"; cat > "${temp}"; echo "${temp}"' < "${script}")"
exec ssh -qt "${remote}" "${temp}" "${@@Q}" ";" rm "${temp}"
